
[editor]
color-modes = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
