# source "$REPOSITORY/powerline/bindings/tmux/powerline.conf"

set -g default-terminal "screen-256color"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

set -g pane-border-style "fg=#444444"
set -g pane-active-border-style "fg=#88c0d0"

set -g pane-border-lines heavy
set -g window-active-style 'fg=terminal,bg=black'
set -g pane-border-status top
set -g pane-border-format "(#{pane_index}) #{pane_title}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Setting to make claude code work better
set -g allow-passthrough on
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -sg escape-time 0
set -g set-clipboard on
set -g history-limit 250000
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
